package com.chen.mybatis.pojo;

public class Dept {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dept.deptno
     *
     * @mbggenerated Sat Jul 30 19:50:33 CST 2022
     */
    private Integer deptno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dept.dname
     *
     * @mbggenerated Sat Jul 30 19:50:33 CST 2022
     */
    private String dname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dept.loc
     *
     * @mbggenerated Sat Jul 30 19:50:33 CST 2022
     */
    private String loc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dept.deptno
     *
     * @return the value of dept.deptno
     *
     * @mbggenerated Sat Jul 30 19:50:33 CST 2022
     */
    public Integer getDeptno() {
        return deptno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dept.deptno
     *
     * @param deptno the value for dept.deptno
     *
     * @mbggenerated Sat Jul 30 19:50:33 CST 2022
     */
    public void setDeptno(Integer deptno) {
        this.deptno = deptno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dept.dname
     *
     * @return the value of dept.dname
     *
     * @mbggenerated Sat Jul 30 19:50:33 CST 2022
     */
    public String getDname() {
        return dname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dept.dname
     *
     * @param dname the value for dept.dname
     *
     * @mbggenerated Sat Jul 30 19:50:33 CST 2022
     */
    public void setDname(String dname) {
        this.dname = dname == null ? null : dname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dept.loc
     *
     * @return the value of dept.loc
     *
     * @mbggenerated Sat Jul 30 19:50:33 CST 2022
     */
    public String getLoc() {
        return loc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dept.loc
     *
     * @param loc the value for dept.loc
     *
     * @mbggenerated Sat Jul 30 19:50:33 CST 2022
     */
    public void setLoc(String loc) {
        this.loc = loc == null ? null : loc.trim();
    }
}